export enum MediaOwnerType {
  TRAINER_PROFILE = 'TRAINER_PROFILE',
  TRAINER_PHOTO_ALBUM = 'TRAINER_PHOTO_ALBUM',
  TRAINER_VIDEO_ALBUM = 'TRAINER_VIDEO_ALBUM',
  TRAINER_FEATURE_VIDEO = 'TRAINER_FEATURE_VIDEO',
  TRAINER_REVIEW = 'TRAINER_REVIEW',
  TRAINER_INTRODUCTION = 'TRAINER_INTRODUCTION',

  CENTER_PROFILE = 'CENTER_PROFILE',
  CENTER_PHOTO_ALBUM = 'CENTER_PHOTO_ALBUM',
  CENTER_VIDEO_ALBUM = 'CENTER_VIDEO_ALBUM',
  CENTER_FEATURE_VIDEO = 'CENTER_FEATURE_VIDEO',

  USER_PROFILE = 'USER_PROFILE',

  PARTNER_PROFILE = 'PARTNER_PROFILE',

  MEMBER_PROFILE = 'MEMBER_PROFILE',

  CLIENT_PROFILE = 'CLIENT_PROFILE',
  CLIENT_REVIEW = 'CLIENT_REVIEW',

  EXERCISE_PHOTO = 'EXERCISE_PHOTO',
  EXERCISE_VIDEO = 'EXERCISE_VIDEO',

  CATEGORY_PHOTO = 'CATEGORY_PHOTO'
}


export class MediaOwnerTypeMapper {
  static toBackend(value: MediaOwnerType): string {
    return value;
  }

  static fromBackend(value: string): MediaOwnerType {
    return MediaOwnerType[value as keyof typeof MediaOwnerType];
  }
}
